package AlgoTrucoClases;

public enum Tantos {
	ENVIDO, REALENVIDO, ENVIDOENVIDO, ENVIDOREALENVIDO, ENVIDOENVIDOREALENVIDO, /*ENVIDOFALTAENVIDO, ENVIDOENVIDOFALTAENVIDO, ENVIDOREALENVIDOFALTAENVIDO, ENVIDOENVIDOREALENVIDOFALTAENVIDO, REALENVIDOFALTAENVIDO, No creo que hacen falta*/ FALTAENVIDO;
}
